### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by Donopotter** [The-Nexus-Project/Limitless-5#100]
### Are you using OptiFine?
No.

### Describe your issue, what happened?
Impossible to launch server on linux

### To Reproduce
Install server directly on linux OS

### Expected behavior
Launch my server

### Screenshots

root@donopotter:/home/tmp# java -jar forge-1.18.2-40.1.48-installer.jar
JVM info: Private Build - 17.0.3 - 17.0.3+7-Ubuntu-0ubuntu0.22.04.1
java.net.preferIPv4Stack=true
Found java version 17.0.3
Exception in thread "main"
java.awt.HeadlessException:
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
        at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
        at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1695)
        at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:676)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:647)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:177)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)

### Affected Version
1.18.2 Forge : 40.1.48
- Pack Version:  1.18.2
- On a server?: Yes

The Server need a display to launch the first time, a chance i have a windows so i can run it one time before upload on my VPS but , if you try to install the modpack server directly to your linux machine u will get this error.

to prevent this error , launch the server on a windows like usualy and after , put your folder in your linux.

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-5/issues/95

**Comment by Gbergz** [comment]
remove the mod ServerConfigUpdater

**Comment by Donopotter** [comment]
i have deleted the mod ServerConfigUpdater and its not working more

**Comment by CephalonRho** [comment]
This is different, it's just because the Forge installer has a GUI when launched without parameters. To install Forge on headless systems use `--installServer`.

**Comment by Donopotter** [comment]
i have deleted the mod ServerConfigUpdater and its not working

**Comment by Donopotter** [comment]
okay now i see thank u
