### ISSUE TITLE
[Issue]: AE2 Things Causing Crash On Joining World When Updating Forge To 40.2.1

### ISSUE THREAD

**Issue by RConTRS** [The-Nexus-Project/Limitless-5#227]
### What happened?

AE2 Things Is Causing Crash On Joining World After Updating Forge To 40.2.1
Downgrading To 40.2.0 Fixes The Problem

### Pack Version

Pack Version : 2.30.0

### To Reproduce

1. Update Forge To 40.2.1
2. Create/Join Any World
3. The Game Freezes Then Crash

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129880_(net.minecraft.resources.ResourceKey)" because "server" is null
	at io.github.projectet.ae2things.util.StorageManager.getInstance(StorageManager.java:84) ~[AE2-Things-1.0.4.jar%2362!/:1.0.4] {re:mixin,re:classloading}
	at io.github.projectet.ae2things.AE2Things.worldTick(AE2Things.java:131) ~[AE2-Things-1.0.4.jar%2362!/:1.0.4] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:895) ~[forge-1.18.2-40.2.1-universal.jar%23611!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1717) ~[client-1.18.2-20220404.173914-srg.jar%23606!/:?]
```

**Comment by Gbergz** [comment]
> Downgrading To 40.2.0 Fixes The Problem
stay on 40.2.0

**Comment by RConTRS** [comment]
ye i see
