### ISSUE TITLE
[Issue]: One mod preventing server from starting

### ISSUE THREAD

**Issue by JaZaKa** [The-Nexus-Project/Limitless-5#231]
### What happened?

This single mod seams to prevent my server from starting.

![Screenshot 2023-04-20 194124](https://user-images.githubusercontent.com/131392731/233445696-ba27b972-ad18-4625-b644-75aff7115f6f.png)

### Pack Version

Version: 2.32.0

### To Reproduce

1. Start server.
2. Error occurs after 5 min. of waiting.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
FarmersRespite-1.18.2-1.3.0.jar                   |Farmer's Respite              |farmersrespite                |1.18.1-1.3.0        |SIDED_SETU|Manifest: NOSIGNATURE
                some-assembly-required-1.18.2-2.0.8.jar           |Some Assembly Required        |some_assembly_required        |1.18.2-2.0.8        |SIDED_SETU|Manifest: NOSIGNATURE
                NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |SIDED_SETU|Manifest: NOSIGNATURE
                infinitylib-2.1.4.jar                             |InfinityLib                   |infinitylib                   |1.18.2-2.1.4        |SIDED_SETU|Manifest: NOSIGNATURE
                agricraft-1.18.2-3.1.4.jar                        |AgriCraft                     |agricraft                     |1.18.2-3.1.4        |ERROR     |Manifest: NOSIGNATURE
                SoL-Carrot-1.18.1-1.12.0.jar                      |Spice of Life: Carrot Edition |solcarrot                     |1.18.1-1.12.0       |SIDED_SETU|Manifest: NOSIGNATURE
                apexcore-1.18.2-4.13.0.jar                        |ApexCore                      |apexcore                      |4.13.0              |SIDED_SETU|Manifest: NOSIGNATURE
                fantasyfurniture-1.18.2-3.14.0.jar                |Fantasy's Furniture           |fantasyfurniture              |3.14.0              |SIDED_SETU|Manifest: NOSIGNATURE
                moredragoneggs-3.1.jar                            |More Dragon Eggs              |moredragoneggs                |3.1                 |SIDED_SETU|Manifest: NOSIGNATURE
                refinedstorageaddons-0.8.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.2               |SIDED_SETU|Manifest: NOSIGNATURE
                Applied-Mekanistics-1.2.2.jar                     |Applied Mekanistics           |appmek                        |1.2.2               |SIDED_SETU|Manifest: NOSIGNATURE
                AEAdditions-1.18.2-3.2.7.jar                      |AE Additions                  |ae2additions                  |3.2.7               |SIDED_SETU|Manifest: NOSIGNATURE
                expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
                ChiselsBits-forge-1.18.2-1.2.116-universal.jar    |Chisels & bits                |chiselsandbits                |1.2.116             |SIDED_SETU|Manifest: NOSIGNATURE
        Crash Report UUID: 2f3b2a1f-3258-4f3d-a520-dfff6b6487dc
        FML: 40.2
        Forge: net.minecraftforge:40.2.0
        FramedBlocks BlockEntity Warning: Not applicable
        Kiwi Modules:
                kiwi:contributors
                kiwi:data
                lightingwand:core[19:24:28] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        AgriCraft (agricraft) encountered an error during the common_setup event phase
?7java.lang.NoSuchFieldError: MECHANICAL_HARVESTER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.2.0.jar%23546!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%23546!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%23546!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.0.jar%23546!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.0.jar%23546!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33) ~[forge-1.18.2-40.2.0-universal.jar%23550!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23545!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Comment by Gbergz** [comment]
Your agricraft config has been corrupted/been reset. Download the instance zip file and take the config folder from there and replace yours.

**Comment by JaZaKa** [comment]
It was a new server, so i just nuked it and reinstalled from the ground up.
Even redownloaded the .zip file.

But it still has the same issue as before.
[crash-2023-04-20_20.17.14-fml.txt](https://github.com/The-Nexus-Project/Limitless-5/files/11289254/crash-2023-04-20_20.17.14-fml.txt)

**Comment by Gbergz** [comment]
Your AgriCraft config is still corrupt, you need the one from the server files. I can send you the new one.
[agricraft.zip](https://github.com/The-Nexus-Project/Limitless-5/files/11289268/agricraft.zip)

**Comment by JaZaKa** [comment]
I'm not sure what I'm suppose to do with this zip file ^^'

**Comment by JaZaKa** [comment]
Thx, it works now.

**Comment by JaZaKa** [comment]
Um so.. New issue.

Should I report a new issue, or can we continues off of this one?

![image](https://user-images.githubusercontent.com/131392731/233460863-ec39d5ba-9411-446c-94d1-d66795efee10.png)

**Comment by Gbergz** [comment]
new issue would be preferable, but here we are so doesn't matter.
Reinstall the client & server. 
Not sure why you're having so many issues tbh.

**Comment by JaZaKa** [comment]
Just dug through the "latest.log"

[20:43:10] [main/WARN]: Mod file C:\Users\JaZaKa\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[20:43:10] [main/WARN]: Mod file C:\Users\JaZaKa\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20:43:10] [main/WARN]: Mod file C:\Users\JaZaKa\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20:43:10] [main/WARN]: Mod file C:\Users\JaZaKa\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar is missing mods.toml file

Wouldn't this implied that the issue is client side?
[latest.log](https://github.com/The-Nexus-Project/Limitless-5/files/11289641/latest.log)

**Comment by Gbergz** [comment]
Nope, those "errors" you posted are normal. and can be ingored.

**Comment by JaZaKa** [comment]
So the issues still seams to be server side?

**Comment by Gbergz** [comment]
Yes maybe, but I would reinstall your client and server to be sure.

**Comment by Gbergz** [comment]
and if the agricraft config is bugging again for some reason, you can always grab it from the message above again.

**Comment by JaZaKa** [comment]
Ok, I'll give you a stop by step prosses of what I'm doing.

**Comment by JaZaKa** [comment]
From clean wipe:

1. 
- Click server icon in Curse:
![image](https://user-images.githubusercontent.com/131392731/233465880-bd17ed2b-5e62-455c-842f-51eb957924b7.png)

2. 
- Get the "mini" zip file 
- Unzip and follow link in REDME.txt fil.
![image](https://user-images.githubusercontent.com/131392731/233466794-63f72254-c64f-432d-8e0b-f575213297cb.png)

3. 
- Downloads the "Full" zip file and unzips it.

4.
- Run forge-1.18.2-40.2.0-installer.jar
- Select "Install server" and click "..."
- Select an empty folder on my desktop "TNP5", hit ok and wait for the "Successfully downloaded" prompt.
![image](https://user-images.githubusercontent.com/131392731/233469791-53e0320f-5800-41c4-84d6-3e10375adc21.png)

5.
- Run the run.bat once
- Set eula to true
- Run run.bat again
- Close server once started 

6.
- Now I add the mods from the "Full" folder, to the "mods" folder in the  TNP5 folder I just made.
![image](https://user-images.githubusercontent.com/131392731/233471803-b9518d14-f3e6-472a-8d16-fef8699bd8ad.png)

7.
- Now I run the "run.bar" file again
- Have the issue with agricraft again (Fixed using the file you sendt)
- Run server again.

8.
- forgot to change the port (I'm running multiple servers)
- Restart server again...

And now I'm here again:
![image](https://user-images.githubusercontent.com/131392731/233476560-08d61124-1ed2-45b1-9e19-e322b80ca681.png)

**Comment by Gbergz** [comment]
It feels like you are overcomplicating it a little bit? It's really much easier than you're explaining it. 
And all the steps are in the readme file included.

Also why did you do this?: 
"Now I add the mods from the "Full" folder, to the "mods" folder in the TNP5 folder I just made."
(issue might just be this extra step that is not needed.)

Everything is already in the server files including mods, config folder defaultconfigs etc. No need to make a mods folder at all.
All you basically have to do is just running the `forge-1.18.2-40.2.0-installer.jar` and outputting to the folder it is currently sitting in, then launching the server with the run.bat. 

And the AgriCraft issue should really be **non-existant**, no idea why you are getting that error. Honestly.

I have now double checked on my end that everything is working I even did it on a second pc aswell just to be sure, and it runs fine. No issues regarding agricraft or the "mod version doesn't match issue" appear.

Trying my best to help.

**Comment by JaZaKa** [comment]
It finally works, thank you so much!

And sorry for just not doing the things right ^^'

**Comment by Gbergz** [comment]
Awesome, and no worries :)
